version: "3"

services:
  api:
    build:
      context: ./services/api
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  redis:
    image: redis/redis-stack:latest
    user: root
    restart: always
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: --requirepass foo
    volumes:
      - ./data_redis:/var/lib/redis/data
  postgresql:
    build:
      context: ./services/postgresql
      args:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
  data_redis:
