version: "3"

services:
  api:
    build:
      context: ./services/api
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
  postgresql:
    build:
      context: ./services/postgresql
      args:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  postgresql-data:
