version: "3"

services:
  api:
    build:
      context: ./services/api
    ports:
      - "8080:8080"
    depends_on:
      - postgresql
    networks:
      - tiny-network
  redis:
    build:
      context: ./services/redis
    ports:
      - "6379:6379"
  postgresql:
    build:
      context: ./services/postgresql
      args:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - tiny-network

volumes:
  postgresql-data:

networks:
  tiny-network:
