global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'api'
    metrics_path: /
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['api:8080']

  - job_name: 'kafka'
    metrics_path: /
    params:
      module: [http_2xx]
    static_configs:
      - targets: ['kafka:9092']
