name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into server and pull repository
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.PRIVATE_KEY }}

          # Command to run on the server
          script: |
            cd /root/tiny-world
            git pull
            docker-compose pull
            docker-compose build
            docker-compose up -d
        env:
          SHOW_OUTPUT: "true"
